---
# Source: microservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linux2
  namespace: linux2
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc1-linux2
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: linux2
automountServiceAccountToken: true
---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: linux2
  namespace: linux2
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc1-linux2
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: linux2
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc1-linux2
    app.kubernetes.io/component: linux2
---
# Source: microservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux2
  namespace: linux2
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc1-linux2
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: linux2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
      app.kubernetes.io/instance: poc1-linux2
      app.kubernetes.io/component: linux2
  template:
    metadata:
      labels:
        helm.sh/chart: microservice-0.1.0
        app.kubernetes.io/name: microservice
        app.kubernetes.io/instance: poc1-linux2
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: linux2
    spec:
      serviceAccountName: linux2
      containers:
        - name: microservice
          securityContext:
            {}
          image: "ghcr.io/liamawhite/microservice:latest"
          imagePullPolicy: IfNotPresent
          args:
            - "-port=8080"
            - "-service-name=linux2"
            - "-timeout=30s"
            - "-log-level=info"
            - "-log-format=json"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
