kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster-1
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 40080
    protocol: TCP
- role: worker
- role: worker