---
# Windows Service - WITHOUT Istio sidecar injection
# This represents a Windows container that cannot run Envoy sidecar
apiVersion: v1
kind: ServiceAccount
metadata:
  name: windows-app
  namespace: windows
  labels:
    app: windows-app
    component: windows-app
---
apiVersion: v1
kind: Service
metadata:
  name: windows-app
  namespace: windows
  labels:
    app: windows-app
    component: windows-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: windows-app
    component: windows-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-app
  namespace: windows
  labels:
    app: windows-app
    component: windows-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-app
      component: windows-app
  template:
    metadata:
      labels:
        app: windows-app
        component: windows-app
      annotations:
        # CRITICAL: Disable Istio sidecar injection for Windows container
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: windows-app
      containers:
        - name: microservice
          image: "ghcr.io/liamawhite/microservice:latest"
          imagePullPolicy: IfNotPresent
          args:
            - "-port=8080"
            - "-service-name=windows-app"
            - "-timeout=30s"
            - "-log-level=info"
            - "-log-format=json"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"