---
# Linux namespace with Istio injection
apiVersion: v1
kind: Namespace
metadata:
  name: linux
  labels:
    istio-injection: enabled
---
# Source: microservice/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linux
  namespace: linux
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc2-linux
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: linux
automountServiceAccountToken: true
---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: linux
  namespace: linux
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc2-linux
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: linux
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc2-linux
    app.kubernetes.io/component: linux
---
# Source: microservice/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux
  namespace: linux
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: poc2-linux
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
      app.kubernetes.io/instance: poc2-linux
      app.kubernetes.io/component: linux
  template:
    metadata:
      labels:
        helm.sh/chart: microservice-0.1.0
        app.kubernetes.io/name: microservice
        app.kubernetes.io/instance: poc2-linux
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: linux
    spec:
      serviceAccountName: linux
      containers:
        - name: microservice
          securityContext:
            {}
          image: "ghcr.io/liamawhite/microservice:latest"
          imagePullPolicy: IfNotPresent
          args:
            - "-port=8080"
            - "-service-name=linux"
            - "-timeout=2s"
            - "-log-level=info"
            - "-log-format=json"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
