# Values for a proper nginx-based proxy gateway instead of using the microservice
nameOverride: "windows-proxy-gateway"
fullnameOverride: "poc1-windows-proxy-gateway"

image:
  repository: nginx
  tag: "1.25"

# Override to use nginx instead of microservice
deployment:
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-proxy-config

service:
  type: ClusterIP
  ports:
  - name: https-mtls
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: http-plain  
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: https-admin
    port: 8443
    targetPort: 8443
    protocol: TCP

podAnnotations:
  sidecar.istio.io/inject: "true"

# Use the istio gateway label to match our existing configuration
labels:
  istio: windows-gateway